---
title: "Tryout"
author: "Shengtao Wang"
---

```{r setup}
library(microbiome)
library(survival)
library(tidyverse)
library(LDM)
library(coxphf)
library(ggpubr)
```

# 1. Data Processing

```{r}
data = import_biom('D:/Default_Working_Directory/Data/MOUTH/converted_otu.biom')
MOUTH.meta = read.csv('D:/Default_Working_Directory/Data/MOUTH/mouth_metadata_sept2020.csv')
MOUTH.otu = as.data.frame(t(data@otu_table))

otu_2_abundance = function(otu.table){
    # Input an OTU table with columns being OTUs.
    lib.size = rowSums(otu.table)
    
    event = as.data.frame(otu.table > 0)*1  # 0 -> below detection limit -> "censored/alive" -> event = 0 (FALSE)
    abundance = -log((otu.table + !event)/lib.size)
    
    return(list(event = event, abundance = abundance))
}

abundance = otu_2_abundance(MOUTH.otu)
MOUTH.abundance = abundance[['abundance']]
MOUTH.event = abundance[['event']]
```

```{r}
# Filtering
MOUTH.meta = filter(MOUTH.meta, Group == 'JHH') %>% arrange(burkid)
MOUTH.meta = MOUTH.meta[complete.cases(MOUTH.meta),]

MOUTH.otu = mutate(MOUTH.otu, burkid = rownames(MOUTH.otu)) %>%
    filter(burkid %in% MOUTH.meta$burkid) %>% arrange(burkid)
MOUTH.abundance = mutate(MOUTH.abundance, burkid = rownames(MOUTH.abundance)) %>%
    filter(burkid %in% MOUTH.meta$burkid) %>% arrange(burkid)
MOUTH.event = mutate(MOUTH.event, burkid = rownames(MOUTH.event)) %>%
    filter(burkid %in% MOUTH.meta$burkid) %>% arrange(burkid)

save(MOUTH.meta, file = 'D:/Default_Working_Directory/Data/MOUTH/MOUTH.meta_filtered.rData')
save(MOUTH.otu, file = 'D:/Default_Working_Directory/Data/MOUTH/MOUTH.otu_filtered.rData')
save(MOUTH.abundance, file = 'D:/Default_Working_Directory/Data/MOUTH/MOUTH.abundance_filtered.rData')
save(MOUTH.event, file = 'D:/Default_Working_Directory/Data/MOUTH/MOUTH.event_filtered.rData')
```

```{r}
load('D:/Default_Working_Directory/Data/MOUTH/MOUTH.meta_filtered.rData')
load('D:/Default_Working_Directory/Data/MOUTH/MOUTH.otu_filtered.rData')
load('D:/Default_Working_Directory/Data/MOUTH/MOUTH.abundance_filtered.rData')
load('D:/Default_Working_Directory/Data/MOUTH/MOUTH.event_filtered.rData')

sum.events = colSums(MOUTH.event[,-28265])  # The last column is id
otus50 = colnames(MOUTH.event[,-28265])[sum.events>50]  # About 10%

MOUTH.otu = MOUTH.otu[,otus50]
MOUTH.abundance = MOUTH.abundance[,otus50]
MOUTH.event = MOUTH.event[,otus50]

num.subject = dim(MOUTH.abundance)[1]
num.otu = dim(MOUTH.abundance)[2]
```

# 2. Coxph

```{r}
model.coxph = function(abundance.tab, event.tab, meta.tab){
    num.subject = dim(abundance.tab)[1]
    num.otu = dim(abundance.tab)[2]
    fit.coxph = matrix(rep(NA, num.otu*3), nrow = num.otu)
    colnames(fit.coxph) = c('Estimates', 'SE', 'p')
    
    for (i in 1:num.otu){
        data.fit = cbind(abundance.tab[,i], event.tab[,i], meta.tab)
        colnames(data.fit)[1:2] = c('abundance', 'event')
        fit = coxph(Surv(time = abundance, event =  event) ~ c_hiv, data = data.fit)
        fit.coxph[i,] = summary(fit)$coefficients[,c(1, 3, 5)]
    }
    
    return(fit.coxph)
}

fit.coxph = model.coxph(MOUTH.abundance, MOUTH.event, MOUTH.meta)
```

# 3. Coxphf

```{r}
fit.coxphf = matrix(rep(NA, num.otu*3), nrow = num.otu)
colnames(fit.coxphf) = c('Estimates', 'SE', 'p')
    
for (i in 1:num.otu){
    data.fit = cbind(MOUTH.abundance[,i], MOUTH.event[,i], MOUTH.meta)
    colnames(data.fit)[1:2] = c('abundance', 'event')
    fit = coxphf(Surv(time = abundance, event =  event) ~ c_hiv, data = data.fit)
    fit.coxphf[i,] = c(fit$coefficients, fit$var^0.5, fit$prob)
}
```

# 4. Coxphf Permutation

## 4.1 Timing

```{r}
Round = 100

perm.matrix = matrix(nrow = Round, ncol = num.otu)
colnames(perm.matrix) = colnames(MOUTH.abundance)

time.permute = rep(NA, Round)

t.start = Sys.time()

for (i in 1:Round){
    
    fit.permuted = rep(NA, num.otu)
    fit.time = rep(NA, num.otu)
    
    for (j in 1:num.otu){
        data.fit  = as.data.frame(cbind(MOUTH.abundance[,j],
                                        MOUTH.event[,j],
                                        sample(MOUTH.meta$Oral_SPF10, num.subject, replace = FALSE)))
        colnames(data.fit) = c('abundance', 'event', 'Oral_SPF10')
        
        t0.fit = Sys.time()
        fit = coxphf(Surv(time = abundance, event = event)~Oral_SPF10, pl = FALSE, data = data.fit)
        t1.fit = Sys.time()
        
        fit.permuted[j] = fit$coefficients
        fit.time[j] = t1.fit - t0.fit
    }
    
    perm.matrix[i,] = fit.permuted
    time.permute[i] = sum(fit.time)
}

t.end = Sys.time()

t.end-t.start
sum(time.permute,na.rm = T)

# Total Time: 221s
# Fit Time: 209s
```

## 4.2 Permutation

```{r}
permutation.coxphf = function(Round = 100){
    
    perm.matrix = matrix(nrow = Round, ncol = num.otu)
    colnames(perm.matrix) = colnames(MOUTH.abundance)
    
    for (i in 1:Round){
    
        fit.permuted = rep(NA, num.otu)
    
        for (j in 1:num.otu){
            data.fit  = as.data.frame(cbind(MOUTH.abundance[,j],
                                            MOUTH.event[,j],
                                            sample(MOUTH.meta$Oral_SPF10, num.subject, replace = FALSE)))
            colnames(data.fit) = c('abundance', 'event', 'Oral_SPF10')
            
            fit = coxphf(Surv(time = abundance, event = event)~Oral_SPF10, pl = FALSE, data = data.fit)
            fit.permuted[j] = fit$coefficients
        }
    
    perm.matrix[i,] = fit.permuted
    }
    
    return(perm.matrix)
}

K = 30
Round = 1000
for (k in 1:K){
    perm.matrix = permutation.coxphf(Round)
    write.csv(perm.matrix, paste('D:/Default_Working_Directory/Permutations/Permutation_', k, '.csv', sep = ''))
}
```

## 4.3 P Values

```{r}
Permutations = as.data.frame(matrix(NA, ncol = num.otu, nrow = 1000*K))
colnames(Permutations) = otus50

for (k in 1:K){
    Permutations[(1:Round)+(k-1)*Round,] = read.csv(paste('D:/Default_Working_Directory/Permutations/Permutation_', k, '.csv', sep = ''))[,-1]
}
```

```{r}
p.perms = rep(NA, num.otu)

for (i in 1:num.otu){
    
    p.perm = sum(Permutations[,i] >= fit.coxphf[i,1])
    p.perm = min(p.perm, nrow(Permutations) - p.perm)
    p.perm = 2*(p.perm+1)/(nrow(Permutations)+1)
    
    p.perms[i] = p.perm
}

hist(p.perms)
plot(x=-log((1:num.otu)/num.otu,10),-log(sort(p.perms),10));abline(0,1)
```

# 5. LDM

```{r}
ldmfit = ldm(MOUTH.otu~factor(MOUTH.meta$Oral_SPF10))
```

# 6. Results

```{r}
p.coxphf = fit.coxphf[,3]
p.LDM = ldmfit$p.otu.freq[1,]

q.perms = p.adjust(p.perms, 'fdr')
q.coxphf = p.adjust(p.coxphf, 'fdr')
q.LDM = ldmfit$q.otu.freq[1,]

result.p = data.frame(OTU = otus50, coxphf = p.coxphf, LDM = p.LDM, perm = p.perms)
result.q = data.frame(OTU = otus50, coxphf = q.coxphf, LDM = q.LDM, perm = q.perms)

cutoff = 0.1

table('perm'=(result.p$perm < cutoff), 'LDM'=(result.p$LDM < cutoff))
table('perm'=(result.q$perm < cutoff), 'LDM'=(result.q$LDM < cutoff))
```

```{r}
result.q %>% ggplot() +
    geom_point(aes(x = OTU, y = LDM, color = 'LDM'), alpha = 0.5) + 
    geom_point(aes(x = OTU, y = coxphf, color = 'coxphf'), alpha = 0.5) + 
    geom_point(aes(x = OTU, y = perm, color = 'perm'), alpha = 0.5) +
    geom_abline(intercept = 0.1, slope = 0, color = 'red', linetype = 'dashed', lwd = 1) +
    labs(y = 'q values', color = 'Model', title = 'q-values') +
    scale_x_discrete(breaks = c()) +
    scale_y_continuous(breaks = seq(0,1,0.1)) +
    scale_color_manual(values = c('LDM' = '#3b5dc9', 'coxphf' = '#1bd1a5', 'perm' = '#ff7500'))
```

```{r}
result.p %>% ggplot() +
    geom_point(aes(x = OTU, y = LDM, color = 'LDM'), alpha = 0.5) + 
    geom_point(aes(x = OTU, y = coxphf, color = 'coxphf'), alpha = 0.5) + 
    geom_point(aes(x = OTU, y = perm, color = 'perm'), alpha = 0.5) +
    geom_abline(intercept = 0.1, slope = 0, color = 'red', linetype = 'dashed', lwd = 1) +
    labs(y = 'p values', color = 'Model', title = 'p-values') +
    scale_x_discrete(breaks = c()) +
    scale_y_continuous(breaks = seq(0,1,0.1)) +
    scale_color_manual(values = c('LDM' = '#3b5dc9', 'coxphf' = '#1bd1a5', 'perm' = '#ff7500'))
```

```{r}
ggplot(result.p) +
    geom_point(aes(x = perm, y = LDM), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    labs(x = 'Permutation', y = 'LDM', title = 'p values')
```

```{r}
ggplot(result.p) +
    geom_point(aes(x = perm, y = coxphf), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    labs(x = 'Permutation', y = 'Coxphf', title = 'p values')
```

```{r fig.height=9, fig.width=6}
p.LDM2perm =  ggplot(result.p) +
    geom_point(aes(x = perm, y = LDM), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    scale_x_continuous(limits = c(0,1), breaks = seq(0,1,0.2)) +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.2))

p.LDM2perm.log =  ggplot(result.p) +
    geom_point(aes(x = -log(perm, 10), y = -log(LDM, 10)), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed')

p.coxphf2perm =  ggplot(result.p) +
    geom_point(aes(x = perm, y = coxphf), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    scale_x_continuous(limits = c(0,1), breaks = seq(0,1,0.2)) +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.2))

p.coxphf2perm.log =  ggplot(result.p) +
    geom_point(aes(x = -log(perm, 10), y = -log(coxphf, 10)), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed')

p.LDM2coxphf =  ggplot(result.p) +
    geom_point(aes(x = coxphf, y = LDM), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    scale_x_continuous(limits = c(0,1), breaks = seq(0,1,0.2)) +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.2))

p.LDM2coxphf.log =  ggplot(result.p) +
    geom_point(aes(x = -log(coxphf, 10), y = -log(LDM, 10)), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed')

ggarrange(p.LDM2perm, p.LDM2perm.log, p.LDM2coxphf, p.LDM2coxphf.log, p.coxphf2perm, p.coxphf2perm.log, ncol = 2, nrow = 3)
```

```{r fig.height=9, fig.width=6}
q.LDM2perm = ggplot(result.q) +
    geom_point(aes(x = perm, y = LDM), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    scale_x_continuous(limits = c(0,1), breaks = seq(0,1,0.2)) +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.2))

q.LDM2perm.log = ggplot(result.q) +
    geom_point(aes(x = -log(perm, 10), y = -log(LDM, 10)), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed')

q.coxphf2perm = ggplot(result.q) +
    geom_point(aes(x = perm, y = coxphf), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    scale_x_continuous(limits = c(0,1), breaks = seq(0,1,0.2)) +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.2))
    
q.coxphf2perm.log = ggplot(result.q) +
    geom_point(aes(x = -log(perm, 10), y = -log(coxphf, 10)), size = 1) + 
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed')

q.LDM2coxphf = ggplot(result.q) +
    geom_point(aes(x = coxphf, y = LDM), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed') +
    scale_x_continuous(limits = c(0,1), breaks = seq(0,1,0.2)) +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.2))

q.LDM2coxphf.log = ggplot(result.q) +
    geom_point(aes(x = -log(coxphf, 10), y = -log(LDM, 10)), size = 1) +
    geom_abline(slope = 1, intercept = 0, lwd = 1, color = 'red', linetype = 'dashed')

ggarrange(q.LDM2perm, q.LDM2perm.log, q.LDM2coxphf, q.LDM2coxphf.log, q.coxphf2perm, q.coxphf2perm.log, ncol = 2, nrow = 3)
```





